import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link';
import { data } from '../fakeData/fakeData';


export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          data.map( item => <li
            key={item.id}
            onClick={() => router.push({
              pathname: item.slug,
              // query : { name : 'category' },
            }, 
            undefined, { shallow: true }
            )}
          >{item.name}</li> )
         }

{/* {
          data.map( item => <li key={item.id}>
            <Link href={{ pathname: item.slug, query: { name: "test" } }} >
                {item.name}
            </Link>
          </li> )
         } */}
      </main>

    </div>
  )
}

